### ISSUE TITLE
"Cannot locate specified Dockerfile: Dockerfile" if .dockerignore contains Dockerfile

### ISSUE THREAD

**Issue by burton-scalefastr** [spotify/dockerfile-maven#116]
Not sure if this is a dockerfile-maven bug or a docker bug.

But either way dockerfile-maven hides what's really happening.

https://github.com/docker/compose/issues/1329

> I found why. My .dockerignore file contains the Dockerfile.
> Is that a bug or a feature? :)

If you add Dockerfile to your .dockerignore it breaks the plugin.  

But not sure I want Dockerfiles hanging around inside my docker images ....

**Comment by mattnworb** [comment]
To clear up something, `.dockerignore` controls what is sent in the "build context" to the docker daemon. The files present in the context are not necessarily a part of the produced image unless you `ADD` or `COPY` or otherwise include them. So in other words, your `Dockerfile` file is not going to be in the produced image unless you somehow add it.

Looks to me like `docker` itself is smart enough to be able to build the image if `.dockerignore` contains `Dockerfile`:

```
$ cat Dockerfile
FROM ubuntu
RUN ["echo", "hi"]
ADD foo.txt foo.txt

$ docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM ubuntu
 ---> 20c44cd7596f
Step 2/2 : RUN echo hi
 ---> Running in ae176412cf2e
hi
 ---> 841e179191a1
Removing intermediate container ae176412cf2e
Successfully built 841e179191a1

$ echo Dockerfile > .dockerignore

$ docker build .
Sending build context to Docker daemon  3.072kB
Step 1/2 : FROM ubuntu
 ---> 20c44cd7596f
Step 2/2 : RUN echo hi
 ---> Using cache
 ---> 841e179191a1
Successfully built 841e179191a1
```

**Comment by ddgenome** [comment]
This seems to be a duplicate of #91 

@mattnworb the behavior you describe for the `docker` CLI is documented behavior in https://docs.docker.com/engine/reference/builder/#dockerignore-file : 

> You can even use the .dockerignore file to exclude the Dockerfile and .dockerignore files. These files are still sent to the daemon because it needs them to do its job. But the ADD and COPY instructions do not copy them to the image.
