### ISSUE TITLE
Evaluate the possibility for more helpful error messages when repository or tag contain ":" or "/"

### ISSUE THREAD

**Issue by mathiasslawik** [spotify/dockerfile-maven#156]
Hello,

I made some mistakes when configuring the plugin - especially using ":" or "/" in the repository or tag name while I was actually trying to build an image locally. This caused (in my view strange) "Connection reset" errors with localhost while running the plugin which I mistook for far more fundamental issues. Now everything works as expected.

So - maybe the plugin could provide a hint to its users when these errors occur. For example, when having a ":" or "/" in the repository and tag, it could tell the users that they should check their repository and tag names. Or maybe there are additional error messages sent by the Docker daemon that could also be displayed.

However at the end it was my fault not using the plugin correctly.

Best regards,
Mathias

**Comment by mattnworb** [comment]
I think this sounds like a good idea and we’d be happy to review and merge any PRs that add something like this.

**Comment by sabf81** [comment]
Is there any plan to add a better message in the next version of that plugin?
Because I get that exception:
`[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:tag (tag-image) on project docker-flyway: Could not tag Docker image: Request error: POST unix://localhost:80/images/15bace5c91d5/tag?repo=registry.cccc.it%2Fxxxxx%2Fdocker-flyway%3Acccct%2Fdocker-flyway&tag=4.2.0-9-local-1&force=true: 500, body: {"message":"invalid reference format"}: HTTP 500 Internal Server Error -> [Help 1]`
and can`t find out what is wrong.
