### ISSUE TITLE
Plugin Dockerfile doesn't take the proxy configuration of %HOME%/.docker/config.json

### ISSUE THREAD

**Issue by mplescano** [spotify/dockerfile-maven#212]
Bug Report
## Description
From the documentation https://docs.docker.com/network/proxy/
Docker command line passes the proxy configuration to the containers.

## How to reproduce
Execute the plugin maven behind to a proxy

## What do you expect
The container can connect to internet

## What happened instead
Dont connect to internet.

## Software:

- `docker version`: Docker version 17.10.0-ce, build f4ffd25
- Spotify's dockerfile-maven version: 1.4.4

## Full backtrace

Error connection on the containers.

**Comment by ncouse** [comment]
That as far as I understand is a feature of the docker command line client. 

Any applications use the Docker APIs directly such as this plugin, won't include that functionality.

I was looking for similar functionality myself recently that only was implemented in the command line client, which is why I realise this.
